[options]

admin_passwd = admin2026

# Update these paths to match your installation
# Base directory: /home/nyamato/odoo-dev/
addons_path = /home/nyamato/odoo-dev/enterprise-17.0,/home/nyamato/odoo-dev/odoo-17/addons,/home/nyamato/odoo-dev/odoo-17/odoo/addons,/home/nyamato/odoo-dev/odoo-17/custom/3Party-kits,/home/nyamato/odoo-dev/odoo-17/custom/addons

http_port = 8069
