[options]

admin_passwd = admin2026

# Update these paths to match your installation
# Base directory: /home/nyamato/odoo-dev/
addons_path = /home/nyamato/odoo-dev/odoo17/enterprise17,/home/nyamato/odoo-dev/odoo17/addons,/home/nyamato/odoo-dev/odoo17/odoo/addons,/home/nyamato/odoo-dev/odoo17/custom/Baano-main

http_port = 8071
