[options]

admin_passwd = admin2026

# Update these paths to match your installation
# Base directory: /home/nyamato/odoo-dev/
addons_path = /home/nyamato/Downloads/odoo-dev/odoo17/enterprise17,/home/nyamato/Downloads/odoo-dev/odoo17/addons,/home/nyamato/Downloads/odoo-dev/odoo17/odoo/addons
http_port = 8069
