[options]

admin_passwd = admin2026

addons_path = /home/nyamato/odoo-dev/odoo-18/enterprise18,/home/nyamato/odoo-dev/odoo-18/addons,/home/nyamato/odoo-dev/odoo-18/odoo/addons,/home/nyamato/odoo-dev/odoo-18/custom/account-financial-reporting, /home/nyamato/odoo-dev/odoo-18/custom/quadrant18e
http_port = 8070



# odoo-localhost-mailserver-key: lgxv bdgu exnq xsef 