[options]

admin_passwd = admin2026

# Update these paths to match your installation
# Base directory: /home/nyamato/odoo-dev/
addons_path = /home/nyamato/Downloads/odoo-dev/odoo18/enterprise18,/home/nyamato/Downloads/odoo-dev/odoo18/addons,/home/nyamato/Downloads/odoo-dev/odoo18/odoo/addons
http_port = 8070
