[options]

admin_passwd = admin2026

# Update these paths to match your installation
# Base directory: /home/nyamato/odoo-dev/
addons_path = /home/nyamato/odoo-dev/enterprise-19.0,/home/nyamato/odoo-dev/odoo-19/addons,/home/nyamato/odoo-dev/odoo-19/odoo/addons,/home/nyamato/odoo-dev/odoo-19/custom

http_port = 8071
