[options]

admin_passwd = admin2026

# Update these paths to match your installation
# Base directory: /home/nyamato/odoo-dev/
addons_path = /home/nyamato/odoo-dev/odoo19/enterprise19,/home/nyamato/odoo-dev/odoo19/addons,/home/nyamato/odoo-dev/odoo19/odoo/addons,/home/nyamato/odoo-dev/odoo19/custom, /home/nyamato/odoo-dev/odoo19/custom/dangeecarken19e, /home/nyamato/odoo-dev/odoo19/custom/reporting-engine,  /home/nyamato/odoo-dev/odoo19/custom/account-financial-reporting

http_port = 8071
